
<template>
    <div class="flex-center md:p-10 h-full w-full bg-gray-50">
        <div v-if="!!bookingStore.getAccount" class="flex max-w-md w-full sm:rounded-md overflow-hidden h-full sm:border bor">
            <div class="bg-white flex flex-col">
                <div class="p-10" @click="goBack">
                    <ChevronLeftIcon class="w-4"/>
                </div>
                <div class="flex items-center w-full h-full">
                    <p class="text-lg">{{bookingStore.getAccount.name}}</p>
                </div>
            </div>
            <div class="overflow-y-auto flex-1">
                <router-view v-slot="{ Component }">
                    <transition
                        :enter-active-class="state.enterClass"
                        :leave-active-class="state.leaveClass"
                    >
                        <component :is="Component" />
                    </transition>
                </router-view>
            </div>
        </div>
    </div>
</template>

<script setup>
import {ChevronLeftIcon} from "@heroicons/vue/20/solid";
import {useBookingStore} from "../../store/booking/index.ts";
import {onMounted, reactive} from "vue";
import {useRoute} from "vue-router";

const route = useRoute();
const bookingStore = useBookingStore();

const state = reactive({
    enterClass: 'slide-in-right',
    leaveClass: 'slide-out-left',
})

const goBack = ()=>{

}

onMounted(async ()=>{
    await bookingStore.loadStore(route.params.account);

})
</script>


<style scoped>


.slide-in-right {
    position: absolute;
    top: 52px;
    z-index: 100;
    -webkit-animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: slide-in-right 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-13 16:14:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-right{0%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}@keyframes slide-in-right{0%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}

.slide-out-left{
    -webkit-animation:slide-out-left .5s cubic-bezier(.55,.085,.68,.53) both;
    animation:slide-out-left .5s cubic-bezier(.55,.085,.68,.53) both}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-13 16:15:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-out-left{0%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}100%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}}@keyframes slide-out-left{0%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}100%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}}

.slide-out-right{-webkit-animation:slide-out-right .5s cubic-bezier(.55,.085,.68,.53) both;animation:slide-out-right .5s cubic-bezier(.55,.085,.68,.53) both}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-13 16:44:24
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-out-right{0%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}100%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}}@keyframes slide-out-right{0%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}100%{-webkit-transform:translateX(1000px);transform:translateX(1000px);opacity:0}}

.slide-in-left{
    position: absolute;
    top: 52px;
    -webkit-animation:slide-in-left .5s cubic-bezier(.25,.46,.45,.94) both;
    animation:slide-in-left .5s cubic-bezier(.25,.46,.45,.94) both
}
/* ----------------------------------------------
 * Generated by Animista on 2024-2-13 16:44:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-left{0%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}@keyframes slide-in-left{0%{-webkit-transform:translateX(-1000px);transform:translateX(-1000px);opacity:0}100%{-webkit-transform:translateX(0);transform:translateX(0);opacity:1}}
</style>