
<template>
    <div class="h-full w-full relative overflow-clip">
        <div class="flex flex-col p-4 gap-4 h-full">
            <div class="font-semibold">Избери услуга:</div>

            <div v-for="service in bookingStore.getServices"
                 @click="selectService(service)"
                 class="border rounded-md border-gray-250 w-full px-4 py-3 bg-white flex items-center gap-4"
                 :class="{'border-blue-400 text-blue-500 bg-blue-100': service.uuid === state.selectedService?.uuid}">
                <CalendarIcon class="w-8"/>
                <div class="">
                    {{service.name}}
                </div>
            </div>
        </div>
        <transition enter-active-class="slide-in-bottom"
                    leave-active-class="slide-out-bottom"
                    mode="out-in">
            <div v-if="state.selectedService" class="pt-3 px-6 pb-5 w-full border-t border-gray-250 absolute bottom-0 h-min flex gap-4 items-center justify-around">
                <button @click="state.selectedService = null" class="secondary-button h-11 flex-1">
                    Отказ
                </button>
                <button @click="submit" class="primary-button h-11 flex-1">
                    Напред
                </button>
            </div>
        </transition>

    </div>
</template>

<script setup lang="ts">

import {useBookingStore} from "../../store/booking";
import {reactive} from "vue";
import {ServiceI} from "../../services/interfaces";
import {CalendarIcon} from "@heroicons/vue/24/outline";
import {useRouter} from "vue-router";

const bookingStore = useBookingStore();
const router = useRouter();

const state = reactive({
    selectedService: bookingStore.getSelectService,
})

const selectService = (service: ServiceI)=>{
    if(state.selectedService?.uuid === service.uuid){
        state.selectedService = null;
        return;
    }
    state.selectedService = service;
}

const submit = () =>{
    bookingStore.selectService(state.selectedService);
    router.push({name: 'booking.hours'})
}
</script>

<style scoped>
.slide-in-bottom {
    -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    animation: slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-3-16 17:36:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
    0% {
        -webkit-transform: translateY(1000px);
        transform: translateY(1000px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}
@keyframes slide-in-bottom {
    0% {
        -webkit-transform: translateY(1000px);
        transform: translateY(1000px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
}
.slide-out-bottom {
    -webkit-animation: slide-out-bottom 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    animation: slide-out-bottom 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-3-16 17:37:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-bottom {
    0% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
    100% {
        -webkit-transform: translateY(1000px);
        transform: translateY(1000px);
        opacity: 0;
    }
}
@keyframes slide-out-bottom {
    0% {
        -webkit-transform: translateY(0);
        transform: translateY(0);
        opacity: 1;
    }
    100% {
        -webkit-transform: translateY(1000px);
        transform: translateY(1000px);
        opacity: 0;
    }
}

</style>