<script setup>
import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
    <div class="w-screen h-screen">
        <router-view v-slot="{ Component }">
            <transition
                    enter-active-class="fade-in"
                    leave-active-class="fade-out"
                    mode="out-in"
            >
                <component :is="Component" />
            </transition>
        </router-view>
    </div>
</template>

<style>

.faster-fade-enter-active,
.faster-fade-leave-active {
  transition: opacity 0.25s ease;
}

.faster-fade-enter-from,
.faster-fade-leave-to {
  opacity: 0;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
.fade-in {
  -webkit-animation: fade-in 0.35s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in 0.35s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
.fade-out{-webkit-animation:fade-out 0.35s ease-out both;animation:fade-out 0.35s ease-out both}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-23 20:51:56
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes fade-in{0%{opacity:0}100%{opacity:1}}

/* ----------------------------------------------
 * Generated by Animista on 2022-3-23 20:52:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes fade-out{0%{opacity:1}100%{opacity:0}}@keyframes fade-out{0%{opacity:1}100%{opacity:0}}
</style>
